name: Code check and Publish

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]

jobs:
  quality:
    runs-on: ubuntu-latest
    name: Quality Check
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v1
        with:
          version: 1.4.1

      - name: Run Biome
        run: biome ci .

  publish:
    needs: quality
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.11.0
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: publish package
        run: pnpm pub:release
        env:
          NODE_AUTH_TOKEN: ${{secrets.DUB_AUTH_TOKEN}}
